name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-restore --no-build --logger trx --results-directory TestResults

      - name: Test Results
        uses: dorny/test-reporter@b082adf0eced0765477756c2a610396589b8c637 # v2
        if: always() && !cancelled()
        with:
          name: Test Results
          path: src/TestResults/*.trx
          reporter: dotnet-trx
          fail-on-error: true
