name: Release

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package version'
        required: true

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439 # v1.7.2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore Valleysoft.DockerRegistryClient

      - name: Pack
        env:
          PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}
        run: dotnet pack -c Release -p:Version=$PACKAGE_VERSION Valleysoft.DockerRegistryClient
      
      - name: Publish Package
        run: dotnet nuget push "Valleysoft.DockerRegistryClient/bin/Release/*.nupkg" -k ${{secrets.NUGET_ORG_API_KEY}} -s https://nuget.org
