name: Release

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package version'
        required: true

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore Valleysoft.DockerRegistryClient

      - name: Pack
        env:
          PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}
        run: dotnet pack -c Release -p:Version=$PACKAGE_VERSION Valleysoft.DockerRegistryClient
      
      - name: Publish Package
        run: dotnet nuget push "Valleysoft.DockerRegistryClient/bin/Release/*.nupkg" -k ${{secrets.NUGET_ORG_API_KEY}} -s https://nuget.org
