name: Release

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package version'
        required: true

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore Valleysoft.DockerRegistryClient

      - name: Pack
        env:
          PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}
        run: dotnet pack -c Release -p:Version=$PACKAGE_VERSION Valleysoft.DockerRegistryClient
      
      - name: Publish Package
        run: dotnet nuget push "Valleysoft.DockerRegistryClient/bin/Release/*.nupkg" -k ${{secrets.NUGET_ORG_API_KEY}} -s https://nuget.org
